### ISSUE TITLE
Feature Request: Line break

### ISSUE THREAD

**Issue by SierraNB** [kubinka0505/iFunny-Captions#12]
Have the ability to add a line break with \n or something.

**Comment by kubinka0505** [comment]
Until I won't find more stable fix, you can add following code piece to [113rd line of the `Scripts/Caption.pyw` file](https://github.com/kubinka0505/iFunny-Captions/blob/master/Scripts/Caption.pyw#L113=).

```python
from itertools import chain
Text = list(chain.from_iterable([Word.split(r"\n") for Word in Text]))
```

**This will also be present in the future release.**
