### ISSUE TITLE
FFmpeg not found

### ISSUE THREAD

**Issue by Satoscio** [kubinka0505/iFunny-Captions#3]
`C:\Users\Satoscio\Desktop\iFunny-Captions>python __init__.pyw 
Set up utils...

FFmpeg not found! ("D:\Programmi\ffmpeg\ffmpeg-4.3.1-2021-01-01-full_build\bin")
Image will not be processed.`

I have everything installed including FFmpeg but it just doesn't want to work

**Comment by Franzyd** [comment]
I have FFmpeg on PATH and it works on its own when I type `ffmpeg` in cmd, yet iFunny-Captions can't find it
![image](https://user-images.githubusercontent.com/56082757/126067110-c44532e5-f631-4d98-b48c-e6a2fac93ba5.png)

I'll work around it by putting the absolute path in the config, but this is definitely an issue

**Comment by kubinka0505** [comment]
[Absolute path to package required](https://github.com/kubinka0505/iFunny-Captions/wiki/Known-Issues#2-undetectable-packages)
