### ISSUE TITLE
Bug: KeyError immediately on run.

### ISSUE THREAD

**Issue by simply-silver** [kubinka0505/iFunny-Captions#4]
**Used `iFunny-Captions` Version: 3.0** 
**Image URL: [here](https://cdn.discordapp.com/attachments/598942667728093197/842906322516967444/explodefaster.gif) 

**FFmpeg Version (do not input when You made Your own build): 4.4** 
**Console Log:**
```bash
Set up utils...
Traceback (most recent call last):
  File "/home/argent/dev/iFunny-Captions/__init__.pyw", line 48, in <module>
    exec(open("Scripts/Main/Packages_Location/FFmpeg.pyw", encoding = "utf-8").read())
  File "<string>", line 13, in <module>
  File "<string>", line 88, in VariableSearch
  File "/usr/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'Path'
```

All settings are default except for the text and image URL. Running Arch Linux.

**Comment by kubinka0505** [comment]
[Do you have FFmpeg in environment variables?](https://stackoverflow.com/q/58268953)

**Comment by simply-silver** [comment]
ffmpeg is installed and located in `PATH` if that's what you mean. Is there another variable it should be in as well?

**Comment by kubinka0505** [comment]
Added Linux package check with `apt` module
