### ISSUE TITLE
ReadMe.md broken and a bug

### ISSUE THREAD

**Issue by Phinlorian** [kubinka0505/iFunny-Captions#6]
Clicking the google colab link shows you this https://prnt.sc/1qhg9fw

Clicking the youtube showcase shows you this https://prnt.sc/1qhg9qe

Error in code from the .ipynb from the download https://prnt.sc/1qhgand
(to clarify the error is in the SETTINGS_DARKMODE_ENABLED and the SETTINGS_DARKMODE_AFTERHOUR)

**Comment by Phinlorian** [comment]
Also when trying to do the downloaded version when I run Run.sh it says "Python was not found; run without arguments to install from the microsoft store, or disable this shortcut from settings > manage app execution aliases" (I use git bash)

**Comment by Phinlorian** [comment]
just make the showcase functional so i know what the hell to do

**Comment by kubinka0505** [comment]
> Clicking the google colab link shows you this https://prnt.sc/1qhg9fw
>  
> Error in code from the .ipynb from the download https://prnt.sc/1qhgand
> (to clarify the error is in the SETTINGS_DARKMODE_ENABLED and the SETTINGS_DARKMODE_AFTERHOUR)

The notebook JSON emulation is broken and will be fixed and expanded in future releases.

> Clicking the youtube showcase shows you this https://prnt.sc/1qhg9qe

Should be fixed now.

> 
> 
> Also when trying to do the downloaded version when I run Run.sh it says "Python was not found; run without arguments to install from the microsoft store, or disable this shortcut from settings > manage app execution aliases" (I use git bash)

[You probably don't have Python in path](https://stackoverflow.com/a/65349178).

**Comment by Phinlorian** [comment]
The youtube showcase is still broken, its because it's private/the wrong link is put in

And I do have python in path so idk what the problem is there just gonna reinstall and see if that fixed it

**Comment by Phinlorian** [comment]
Also i just reinstalled python and made sure that it was added to path and it still didnt work

**Comment by Phinlorian** [comment]
Ok I got python working, a new problem is when I run Run.bat it says "URL located in cache folder." and the closes and never produces the caption

**Comment by Phinlorian** [comment]
> Ok I got python working, a new problem is when I run Run.bat it says "URL located in cache folder." and the closes and never produces the caption

Just to clarify I do have all the things in requirements.txt downloaded and in path

**Comment by kubinka0505** [comment]
> The youtube showcase is still broken, its because it's private/the wrong link is put in
> 
> And I do have python in path so idk what the problem is there just gonna reinstall and see if that fixed it

Didn't noticed.

> Ok I got python working, a new problem is when I run Run.bat it says "URL located in cache folder." and the closes and never produces the caption

Run `/Utility/Remove_Cache.pyw` from explorer and try again.

**Comment by kubinka0505** [comment]
Fixed `ReadMe.md` and `iFunny-Captions.ipynb`
