### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by Kubrickian** [kubinka0505/iFunny-Captions#8]
**Describe Your feature request:** 

how to add different language, for example cyrllic?

**Comment by kubinka0505** [comment]
Adding custom languages/characters other than Latin depends on the number of supported glyphs in the typeface.<br>**The default, pre-configured font type doesn't include these**.

You can add custom fonts by searching for them online and then following the steps on the [tutorial in the wiki section](http://github.com/kubinka0505/iFunny-Captions/wiki/Custom-Fonts).
